### ISSUE TITLE
footer里面的搜搜索和重置按钮如何跟在表单控件右边？

### ISSUE THREAD

**Issue by alicksnake22** [lljj-x/vue-json-schema-form#14]
![image](https://user-images.githubusercontent.com/14839142/93784007-0689ac80-fc5f-11ea-86b0-26ddde70ced8.png)
footer里面的搜搜索和重置按钮如何跟在表单控件右边？

**Comment by lljj-x** [comment]
我做了个Demo，https://codepen.io/ljj/pen/LYNXqXG

---
需要加点css，后面版本我会把 inlne布局，相关的样式加进去

```css
.genFromComponent.el-form--inline .fieldGroupWrap{
    display: inline-block;
    margin-right: 10px;
    vertical-align: top;
}

.genFromComponent.el-form--inline .validateWidget {
  margin-right: 0;
}
```
